### ISSUE TITLE
DrawText1616 Not working

### ISSUE THREAD

**Issue by Lee-Stratford** [ScoobieSnax/SSD1322-256X64-PYTHON-LIBRARY#1]
Hi 
Just got a SSD1322 and playing with it using your code and having difficulty with the large DrawText1616.
Code is.....
window_one.DrawText1616(0, 0, 'ABCDEFGHIJKLMNOPQRST', 0xf, 0)
window_one.DrawText1616(0, 16, 'UVWXYZ', 0xf, 0)
window_one.DrawText1616(0, 32, 'abcdefghijklmnopqrst', 0xf, 0)
window_one.DrawText1616(0, 48, 'uvwxyz', 0xf, 0)
window_one.DrawScreenBuffer()

When I run the code in the shell it fails giving the error     
window_one.DrawText1616(0, 0, 'ABCDEFGHIJKLMNOPQRST', 0xf, 0)
TypeError: DrawText1616() takes exactly 5 arguments (6 given)

I would be grateful for any help :)

**Comment by ScoobieSnax** [comment]
Hi,
This was an error in the wiki, there is no ‘inv’ parameter in the DrawText1616 command.
The wiki is corrected just now.
Sorry for this and let me know if it work now. I ‘ll add this feature in the future in the DrawText1616 command. I think i was pressed to finish this damn library and the inv paramater was forget 😃
Just for my curiosity what’s your project with the ssd1322 ?

Thanks in advance

Provenance : Courrier pour Windows 10

De : Lee-Stratford
Envoyé le :dimanche 29 septembre 2019 18:37
À : ScoobieSnax/SSD1322-256X64-PYTHON-LIBRARY
Cc : Subscribed
Objet :[ScoobieSnax/SSD1322-256X64-PYTHON-LIBRARY] DrawText1616 Not working(#1)

Hi
Just got a SSD1322 and playing with it using your code and having difficulty with the large DrawText1616.
Code is.....
window_one.DrawText1616(0, 0, 'ABCDEFGHIJKLMNOPQRST', 0xf, 0)
window_one.DrawText1616(0, 16, 'UVWXYZ', 0xf, 0)
window_one.DrawText1616(0, 32, 'abcdefghijklmnopqrst', 0xf, 0)
window_one.DrawText1616(0, 48, 'uvwxyz', 0xf, 0)
window_one.DrawScreenBuffer()
When I run the code in the shell it fails giving the error
window_one.DrawText1616(0, 0, 'ABCDEFGHIJKLMNOPQRST', 0xf, 0)
TypeError: DrawText1616() takes exactly 5 arguments (6 given)
I would be grateful for any help :)

**Comment by Lee-Stratford** [comment]
I bought a cheap D-Link DNS-343 4bay NAS off eBay. Got annoyed at the poor performance.  I bought a Raspberry Pi 4, and was going to rip out the D-link guts and redesign it all with a Pi4 running the system. The D-Link had a 2.8" horrible yellow OLED so bought a 3.2" White on Black SSD1322 instead and reworked the front panel to take the larger display. However, its still all work in progress. My experience is the hardware side of things and not really software, so a software noob! I tend to learn better by playing with code to get an understanding :)

Retried using the Python 2.7 code........

from OLED import OLED
from OLEDWindow import OLEDWindow

oled = OLED() # The OLED hardware driver
window_one = OLEDWindow(oled,0,0,256,64) # Window work size area (all the screen here)

window_one.DrawText1616(0, 0, 'ABCDEFGHIJKLMNOPQRST', 0xf)
window_one.DrawText1616(0, 16, 'UVWXYZ', 0xf)
window_one.DrawText1616(0, 32, 'abcdefghijklmnopqrst', 0xf)
window_one.DrawText1616(0, 48, 'uvwxyz', 0xf)
window_one.DrawScreenBuffer()

It now fails with 

File "/home/pi/Nas-Software/OLED/SSD1322-256X64-PYTHON-LIBRARY-master/OLEDWindow.py", line 534, in DrawText1616
    self.drawImage(x, y, 16, 16, color, FONT_16x16,(ord(c)-32)*32)
AttributeError: OLEDWindow instance has no attribute 'drawImage' 

Always the way, fix one issue and another crops up grrrrrr....sigh....

**Comment by ScoobieSnax** [comment]
It's already fixed ! Just an uppercase problem in the OLEDWindow.py at line 534, use DrawImage instead of drawImage...
You can modify it yourself of redownload the OLEDWindow.py file, it's modified right now.
Let me know if it works !

**Comment by Lee-Stratford** [comment]
Bingo!! I'm chuffed now :) I will be playing with the library in more depth. Started with the standard text and now move onto shapes and images. If I break it again I'll let you know :) 

Thanks :)

**Comment by ScoobieSnax** [comment]
No problem, it's always a pleasure to see someone use my work :-D
Good luck with your project, i wait for your future "break" ;-D
