### ISSUE TITLE
Interesting Project..

### ISSUE THREAD

**Issue by kelvinyasu** [ScoobieSnax/SSD1322-256X64-PYTHON-LIBRARY#2]
Hello....

Awesome project... just wondering how you can get bigger front size?

Kelvin Lo

**Comment by ScoobieSnax** [comment]
Hi,
Thanks for the compliment ;)
I only put 2 fonts size, 5X7 and 16X16. I made this library for a 256X64 screen, these 2 sizes was sufficient for my use.
It's easy (but long !) to add others fonts in OLEDWindow.py --> see 'def DrawText ' and 'def DrawText1616'

Scoob
